import streamlit as st
import joblib
import numpy as np
import pandas as pd
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

# === Load Model ===
model = joblib.load("models/final_model.pkl")

st.title("Heart Disease Prediction App ❤️")

# === Input Form ===
st.header("Patient Information")
patient_name = st.text_input("Patient Name", help="Enter the patient's full name.")
sex = st.selectbox("Sex", options=[0, 1], format_func=lambda x: "Female" if x == 0 else "Male", help="Select patient’s gender.")
cp = st.selectbox("Chest Pain Type (cp)", options=[0, 1, 2, 3], format_func=lambda x: ["Typical angina", "Atypical angina", "Non-anginal pain", "Asymptomatic"][x], help="Type of chest pain.")
thalach = st.number_input("Maximum Heart Rate (thalach)", min_value=50, max_value=250, value=180, help="Max heart rate during stress test.")
exang = st.selectbox("Exercise Induced Angina (exang)", options=[0, 1], format_func=lambda x: "No" if x == 0 else "Yes", help="Angina induced by exercise.")
oldpeak = st.number_input("ST Depression (oldpeak)", min_value=0.0, max_value=10.0, value=1.0, step=0.1)
slope = st.selectbox("Slope of ST Segment (slope)", options=[0, 1, 2], format_func=lambda x: ["Upsloping", "Flat", "Downsloping"][x], help="Slope of ST segment during exercise.")
ca = st.selectbox("Number of Major Vessels (ca)", options=[0, 1, 2, 3, 4], help="Vessels colored by fluoroscopy.")
thal = st.selectbox("Thalassemia (thal)", options=[0, 1, 2, 3], format_func=lambda x: ["Not described", "Normal", "Reversible defect", "Fixed defect"][x], help="Thalassemia condition.")

# Convert to array
input_data = np.array([[sex, cp, thalach, exang, oldpeak, slope, ca, thal]])

def generate_pdf_report(patient_name, sex, cp, thalach, exang, oldpeak, slope, ca, thal, result, probability):
    # Generate filename with patient name and timestamp
    filename = f"heart_report_{patient_name.replace(' ', '_')}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    c = canvas.Canvas(filename, pagesize=letter)
    c.setFont("Helvetica", 12)
    
    # Title and line
    c.drawString(50, 750, "Heart Disease Prediction Report")
    c.line(50, 747, 550, 747)
    
    # Patient details
    c.drawString(50, 720, f"Patient Name: {patient_name}")
    c.drawString(50, 700, f"Date and Time: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(50, 680, f"Sex: {'Female' if sex == 0 else 'Male'}")
    c.drawString(50, 660, f"Chest Pain Type: {['Typical angina', 'Atypical angina', 'Non-anginal pain', 'Asymptomatic'][cp]}")
    c.drawString(50, 640, f"Max Heart Rate (thalach): {thalach}")
    c.drawString(50, 620, f"Exercise Angina (exang): {'No' if exang == 0 else 'Yes'}")
    c.drawString(50, 600, f"Oldpeak: {oldpeak}")
    c.drawString(50, 580, f"Slope: {['Upsloping', 'Flat', 'Downsloping'][slope]}")
    c.drawString(50, 560, f"Number of Major Vessels (ca): {ca}")
    c.drawString(50, 540, f"Thalassemia: {['Not described', 'Normal', 'Reversible defect', 'Fixed defect'][thal]}")
    c.drawString(50, 520, f"Prediction: {result}")
    c.drawString(50, 500, f"Probability: {probability:.2f}")
    c.drawString(50, 480, "Disclaimer: This report is generated by an AI model for informational purposes only.")
    c.drawString(50, 460, "Consult a healthcare professional for medical advice.")
    
    c.save()
    return filename

if st.button("Predict"):
    if not patient_name.strip():
        st.error("Please enter the patient's name.")
    else:
        prediction = model.predict(input_data)[0]
        probability = model.predict_proba(input_data)[0][1]
        result = "Patient is at risk of Heart Disease 💔" if prediction == 1 else "No Heart Disease detected ✅"
        st.subheader("Result:")
        st.write(result)
        st.write(f"Prediction Probability: {probability:.2f}")
        pdf_filename = generate_pdf_report(patient_name, sex, cp, thalach, exang, oldpeak, slope, ca, thal, result, probability)
        with open(pdf_filename, "rb") as f:
            st.download_button("📥 Download Report", f, file_name=pdf_filename, mime="application/pdf")
